# Generated by Django 5.2 on 2025-10-09 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='movies/main_images/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='movies/cover_images/')),
            ],
        ),
        migrations.CreateModel(
            name='CastCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='castcrew/profile_images/')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='castcrew', to='bms.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=1)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bms.movie')),
            ],
        ),
    ]
