# Generated by Django 5.2 on 2025-10-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
