# Generated by Django 5.2 on 2025-10-13 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0004_show_seat_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='show',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='show',
        ),
        migrations.AddField(
            model_name='booking',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bms.movie'),
        ),
        migrations.AddField(
            model_name='seat',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='bms.movie'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Show',
        ),
    ]
